apiVersion: apps/v1
kind: Deployment
metadata:
  name: lnd-msvc
spec:
  selector:
    matchLabels:
      run: lnd-msvc
  replicas: 1
  template:
    metadata:
      labels:
        run: lnd-msvc
    spec:
      containers:
      - name: lnd-msvc
        image: 166720137260.dkr.ecr.us-west-2.amazonaws.com/k8s-lnd-msvc:latest
        ports:
        - containerPort: 8080
